### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Backend#7]
## user story
As a person that enjoys games, I like to play games that have variety to them so that they don't turn repetitive and eventually become boring. If a drawing, trivia and any similar game has only a few questions/themes, I memorize all the answers and it that's not fun. I'd love to play a game that lets me chose from a large variety of categories that I'm interested in so it doesn't get repetitive.

- Persona: A player that is interested in web based games, age can vary
- Feature: See names of players currently on lobby
- Business Value: Other players can see their friends on the lobby and host knows if he can start the game (once all participants are there)

## Tasks

- [x] Look up documentation on MongoDB
- [x] Set up database structure

## Acceptance Criteria
- Structure of database will be set, but database does not need to be filled
- Database should be ready to receive data

**Comment by sjiang1** [comment]
Don't forget to leave a comment and close it :-)

**Comment by BelaReimberg** [comment]
In order to complete this issue the following steps were completed:
- MongoDB account was created
- Cloud Database was setup to allow for connections from multiple machines to a remote server
- Users/credentials were created with specific roles for database modification and data access
- This includes a user with read-only permissions for accessing categories for the game logic
- (Credentials for database connection consist of a username and password)
- Created a cluster for deployment. Within this cluster a database called FictionaryDB was created. 
- Structure: collection was created called 'words'
- Each 'document' (item in MongoDB) within this collection consists of a word and its associated category
- Database is active for administrative connections and ready to receive new data in the aforementioned format
- Credentials for backend use (category/word fetching) will be included with the Digital Ocean deployment information
